openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
